### ISSUE TITLE
Labeled test data for past shared tasks

### ISSUE THREAD

**Issue by d125q** [noisy-text/noisy-text.github.io#1]
Hello.  I am looking to implement noisy text normalization as part of a pipeline I'm building for age/gender classification of authors of tweets.  The 2015 papers have so far been extremely helpful in helping me achieve this task.  However, I feel like having access to the labeled test data would help not just me, but everyone else even further.  The same applies to all other past shared tasks.

Thank you in advance.

**Comment by cocoxu** [comment]
Please email the organizers of the specific shared-task at WNUT you are interested in. They will be happy to share the data with you.
